spring:
  # Default development environment
  profiles:
    active: dev
  jpa:
    # Show SQL
    show-sql: true
  messages:
    basename: i18n/messages/messages
    encoding: UTF-8
    fallbackToSystemLocale: true
  jmx:
    enabled: false
  # thymeleaf
  thymeleaf:
    prefix: classpath:/thymeleaf/
    check-template-location: true
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML5
  # Static file
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations[0]: classpath:/static/
ali:
  dbhub:
    version: 1.0.0
    jdbc-jar-downLoad-urls:
      - https://oss-chat2db.alibaba.com/lib/mysql-connector-java-8.0.30.jar
      - https://oss-chat2db.alibaba.com/lib/mysql-connector-java-5.1.47.jar
      - https://oss-chat2db.alibaba.com/lib/clickhouse-jdbc-0.3.2-patch8-http.jar
      - https://oss-chat2db.alibaba.com/lib/mariadb-java-client-3.0.8.jar
      - https://oss-chat2db.alibaba.com/lib/mssql-jdbc-11.2.1.jre17.jar
      - https://oss-chat2db.alibaba.com/lib/oceanbase-client-2.4.2.jar
      - https://oss-chat2db.alibaba.com/lib/postgresql-42.5.1.jar
      - https://oss-chat2db.alibaba.com/lib/sqlite-jdbc-3.39.3.0.jar
      - https://oss-chat2db.alibaba.com/lib/ojdbc11.jar
      - https://oss-chat2db.alibaba.com/lib/ojdbc8-19.3.0.0.jar
      - https://oss-chat2db.alibaba.com/lib/orai18n-19.3.0.0.jar
      - https://oss-chat2db.alibaba.com/lib/h2-2.1.214.jar
      - https://oss-chat2db.alibaba.com/lib/DmJdbcDriver18-8.1.2.141.jar
      - https://oss-chat2db.alibaba.com/lib/HikariCP-4.0.3.jar
# FlywayDB output execution of SQL log
logging:
  level:
    org:
      flywaydb: debug
# Login function
sa-token:
  # Token name (also the cookie name)
  token-name: DBHUB
  timeout: 2592000
  # Whether the same account is allowed to be published (allowed to log in together when True is allowed to squeeze the old login when it is for False)
  is-concurrent: true
  # When multiple people log in to the same account, whether to share a token (when you log in to all token when you are for True, you will log in to FALSE each time you log in to create a new token)
  is-share: true
  # Token style
  token-style: uuid
  # Whether to output operation log
  is-log: true
  # JWT secrets need to be changed when deploying, otherwise you can crack login casually
  jwt-secret-key: jwt_dbhub
  is-write-header: true

chatgpt:
  apiKey: sk-xxxx
  apiHost: https://api.openai.com/
  # You can choose GPT3 or GPT35
  version: GPT35
  context:
    length: 4
