spring:
  datasource:
    # Configure the relative path with a database
    url: jdbc:h2:~/.chat2db/db/chat2db_dev;MODE=MYSQL
    driver-class-name: org.h2.Driver
  #  Used for database table structure version management
  flyway:
    locations: classpath:db/migration/dev
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true
# The port number
server:
  port: 10821


