spring:
  datasource:
    # Configure the relative path with a database
    url: jdbc:h2:~/.chat2db/db/chat2db;MODE=MYSQL
    driver-class-name: org.h2.Driver
  #  Used for database table structure version management
  flyway:
    locations: classpath:db/migration/release
# The port number
server:
  port: 10824