spring:
  datasource:
    # Configure the relative path with a database
    url: jdbc:h2:~/.chat2db/db/chat2db_test;MODE=MYSQL
    driver-class-name: org.h2.Driver
  #Used for database table structure version management
  # The test of the test is still DEV, but there is a separate library to ensure that multiple clients are running
  flyway:
    locations: classpath:db/migration/dev
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true
# The port number
server:
  port: 10824
